In [3]:
import numpy as np

xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

xAll = xAll / np.amax(xAll, axis=0)
y = y / 100

X = np.split(xAll, [3])[0]
xPredicted = np.split(xAll, [3])[1]

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100

class Neural_Network(object):
    def __init__(self):
        
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        
        self.W1 = np.random.randn(self.inputSize,self.hiddenSize)
        self.W2 = np.random.randn(self.hiddenSize,self.outputSize)

    def forward(self, X):
    
        self.z = np.dot(X,self.W1)
        self.z2 = self.sigmoid(self.z) 
        self.z3 = np.dot(self.z2, self.W2) 
        o = self.sigmoid(self.z3)
        return o

    def sigmoid(self, s):
    
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        
        return s * (1 - s)

    def backward(self, X, y, o):
        
        self.o_error = y - o  
        self.o_delta = self.o_error * self.sigmoidPrime(o)  

        self.z2_error = self.o_delta.dot(self.W2.T)  
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)  

        self.W1 += X.T.dot(self.z2_delta) 
        self.W2 += self.z2.T.dot(self.o_delta)  

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X))))) 
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.41496071]
 [0.41036791]
 [0.4138685 ]]
Loss: 
0.2279783028205006


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.45960681]
 [0.45828334]
 [0.45763452]]
Loss: 
0.18675935725956827


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.50035531]
 [0.50253602]
 [0.4976761 ]]
Loss: 
0.15260006708432364


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.53709946]
 [0.54251095]
 [0.5338089 ]]
Loss: 
0.12476140561850235


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.57001207]
 [0.57809595]
 [0.56615252]]
Loss: 
0.10227954643382016


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actua

Predicted Output: 
[[0.89358216]
 [0.88948677]
 [0.8830053 ]]
Loss: 
0.0005387658562101835


# 127

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89365443]
 [0.88953767]
 [0.8830758 ]]
Loss: 
0.0005381692449861311


# 128

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89372473]
 [0.88958683]
 [0.88314432]]
Loss: 
0.0005375901429393858


# 129

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89379313]
 [0.88963429]
 [0.88321092]]
Loss: 
0.0005370275665891514


# 130

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89385969]
 [0.88968011]
 [0.88327565]]
Loss: 
0.0005364805899331794


# 131

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89392445]
 [0.889

 [0.88547893]]
Loss: 
0.0005045473740089304


# 231

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8963065 ]
 [0.89051351]
 [0.88548396]]
Loss: 
0.0005042836578065936


# 232

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89631397]
 [0.89050709]
 [0.8854889 ]]
Loss: 
0.0005040202284795356


# 233

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89632134]
 [0.89050059]
 [0.88549373]]
Loss: 
0.0005037570832323137


# 234

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89632862]
 [0.89049401]
 [0.88549847]]
Loss: 
0.0005034942194101325


# 235

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8963358 ]
 [0.89048735]
 [0.88550311]]
Loss: 
0.0005032316344911

Predicted Output: 
[[0.89685563]
 [0.8895963 ]
 [0.88575847]]
Loss: 
0.0004765310788888235


# 343

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89685953]
 [0.88958753]
 [0.88575999]]
Loss: 
0.0004762936713951769


# 344

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89686343]
 [0.88957877]
 [0.8857615 ]]
Loss: 
0.00047605647825504894


# 345

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89686731]
 [0.88957001]
 [0.88576301]]
Loss: 
0.0004758194992356775


# 346

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89687119]
 [0.88956125]
 [0.88576451]]
Loss: 
0.0004755827341046955


# 347

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89687507]
 [0.88

Predicted Output: 
[[0.89727567]
 [0.88862389]
 [0.88591863]]
Loss: 
0.00045079322474876523


# 457

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89727921]
 [0.88861565]
 [0.88591999]]
Loss: 
0.0004505788207795011


# 458

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728274]
 [0.88860742]
 [0.88592135]]
Loss: 
0.00045036460631983394


# 459

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728628]
 [0.8885992 ]
 [0.88592271]]
Loss: 
0.0004501505811649968


# 460

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728981]
 [0.88859098]
 [0.88592407]]
Loss: 
0.00044993674511042064


# 461

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89729334]
 [0.

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89761343]
 [0.88784243]
 [0.88605078]]
Loss: 
0.0004306520264056299


# 555

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89761679]
 [0.88783472]
 [0.88605212]]
Loss: 
0.0004304552545372976


# 556

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89762014]
 [0.88782701]
 [0.88605346]]
Loss: 
0.00043025865315047114


# 557

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8976235 ]
 [0.88781931]
 [0.8860548 ]]
Loss: 
0.0004300622220615559


# 558

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89762685]
 [0.88781161]
 [0.88605613]]
Loss: 
0.0004298659610871833


# 559

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0

Predicted Output: 
[[0.89790241]
 [0.88718304]
 [0.88616776]]
Loss: 
0.0004139690366020701


# 643

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89790562]
 [0.88717576]
 [0.88616908]]
Loss: 
0.0004137865867110787


# 644

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89790883]
 [0.88716849]
 [0.8861704 ]]
Loss: 
0.0004136042919209916


# 645

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89791203]
 [0.88716123]
 [0.88617172]]
Loss: 
0.00041342215206578167


# 646

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89791524]
 [0.88715397]
 [0.88617304]]
Loss: 
0.0004132401669796174


# 647

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89791844]
 [0.88

0.00039446207690005825


# 755

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89825494]
 [0.88639057]
 [0.88631513]]
Loss: 
0.0003942960086621692


# 756

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89825797]
 [0.88638382]
 [0.88631642]]
Loss: 
0.0003941300780743949


# 757

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.898261  ]
 [0.88637707]
 [0.88631771]]
Loss: 
0.00039396428499092437


# 758

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89826403]
 [0.88637032]
 [0.88631899]]
Loss: 
0.0003937986292661105


# 759

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89826706]
 [0.88636358]
 [0.88632028]]
Loss: 
0.0003936331107544829


# 760

Input (

 [0.89]]
Predicted Output: 
[[0.89857357]
 [0.88568553]
 [0.8864524 ]]
Loss: 
0.00037714115872737277


# 864

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89857644]
 [0.88567922]
 [0.88645366]]
Loss: 
0.000376989270696231


# 865

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89857931]
 [0.88567292]
 [0.88645491]]
Loss: 
0.000376837505382085


# 866

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89858218]
 [0.88566663]
 [0.88645616]]
Loss: 
0.00037668586265655516


# 867

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89858505]
 [0.88566034]
 [0.88645742]]
Loss: 
0.0003765343423914043


# 868

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89858791

 [0.89]]
Predicted Output: 
[[0.8988564 ]
 [0.88506853]
 [0.88657722]]
Loss: 
0.0003623993934534558


# 965

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89885913]
 [0.88506261]
 [0.88657844]]
Loss: 
0.000362259275851793


# 966

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89886186]
 [0.8850567 ]
 [0.88657965]]
Loss: 
0.0003621192687309756


# 967

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89886459]
 [0.88505079]
 [0.88658087]]
Loss: 
0.0003619793719769502


# 968

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89886731]
 [0.88504488]
 [0.88658209]]
Loss: 
0.0003618395854757903


# 969

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89887004]