In [16]:
# Question 1
import numpy as np
x = np.array([1, 7])
y = np.array([4, 7])
print(x)

[1 7]


In [17]:
print(y)

[4 7]


In [18]:
print(np.greater(x, y))

[False False]


In [19]:
print(np.greater_equal(x, y))

[False  True]


In [20]:
print(np.less(x,y))

[ True False]


In [21]:
print(np.less_equal(x,y))

[ True  True]


In [23]:
#Question 2

ex1=np.zeros((10,10))
print(ex1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
ex2=np.ones((10,10))
print(ex2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
ex3=np.full((10, 10),5)
print(ex3)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [27]:
#Question 3
z = np.array([1,4])
v = np.array([3,8])
print(z)

[1 4]


In [28]:
print(v)

[3 8]


In [30]:
print(z + v)

[ 4 12]


In [31]:
print(z- v)

[-2 -4]


In [32]:
print(z * v)

[ 3 32]


In [33]:
print(z / v)

[0.33333333 0.5       ]


In [35]:
# Question 4
print(np.add(z,v))

[ 4 12]


In [40]:
print(np.subtract(z,v))

[-2 -4]


In [38]:
print(np.multiply(z,v))

[ 3 32]


In [39]:
print(np.divide(z,v))

[0.33333333 0.5       ]


In [44]:
# Question 5
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]


In [47]:

print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [48]:
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [3]:
# Question 6

import pandas as pd
import numpy as np

gradesd  = {"name": ['XXXX', 'YYYY', 'ZZZZ'],
        "score": [7, 5, 5], "qualify": ["yes", "no", "no"]}
labels = ['a', 'b', 'c']

d = pd.DataFrame(gradesd , index=labels)
print(d)

   name  score qualify
a  XXXX      7     yes
b  YYYY      5      no
c  ZZZZ      5      no


In [5]:
# Question 7

print(d[["name", "score"]])


   name  score
a  XXXX      7
b  YYYY      5
c  ZZZZ      5


In [6]:
# Question 8
import pandas as pd

In [7]:
student1 = pd.DataFrame({"id":["S1", "S2", "S3", "S4"], 
                         "name": ["Rene", "Andres", "Carlos","Francisca"],"marks": [100, 200, 250, 300]})
student2 = pd.DataFrame({"id":["S5", "S6", "S7", "S8"], 
                         "name":["Jorge", "Claudia", "Pamela", "Juan"], "marks": [150, 250, 300, 350]})

In [8]:
data = pd.concat([student1, student2])
print(data)

   id       name  marks
0  S1       Rene    100
1  S2     Andres    200
2  S3     Carlos    250
3  S4  Francisca    300
0  S5      Jorge    150
1  S6    Claudia    250
2  S7     Pamela    300
3  S8       Juan    350


In [14]:
# Question 9

import pandas as pd
import numpy as np

d = pd.DataFrame({"customer_id":[1, 2, 3, 4, 5],
                 "purchase_amount":[100, np.nan, 200, np.nan, 300],
                 "order_date":["2020-10-05", "2020-09-10", "2020-08-07", np.nan, np.nan]})

print(d)

   customer_id  purchase_amount  order_date
0            1            100.0  2020-10-05
1            2              NaN  2020-09-10
2            3            200.0  2020-08-07
3            4              NaN         NaN
4            5            300.0         NaN


In [15]:
print(d.isna())

   customer_id  purchase_amount  order_date
0        False            False       False
1        False             True       False
2        False            False       False
3        False             True        True
4        False            False        True


In [19]:
# Question 10

import pandas as pd

d = pd.Series([1,2,3,4,5])
print(d)SS


0    1
1    2
2    3
3    4
4    5
dtype: int64
