<a href="https://colab.research.google.com/github/ReneValenzuela/AI-ML-Batch2/blob/master/Darshan_AIML_B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('darshan-aiml-b2')
jovian.set_colab_id('1c-JbqsFZsdtt1L_9uQ9rrP96KDXcBxZB')

In [ ]:
import warnings
warnings.simplefilter('ignore')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
# pickle is used to save the model created by us

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/ingledarshan/Data-Science-Advanced-Datasets/main/hiring.csv')
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [ ]:
df.shape

(8, 4)

In [ ]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [ ]:
df['experience'].fillna(0, inplace=True)

In [ ]:
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [ ]:
df['test_score'].mean()

7.857142857142857

In [ ]:
df['test_score'].fillna(df['test_score'].mean(), inplace=True)

In [ ]:
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

__Data is Clean now.__

In [ ]:
df.head()

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [ ]:
X = df.iloc[:,:-1]

In [ ]:
X.head()

experience  test_score  interview_score
0          0         8.0                9
1          0         8.0                6
2       five         6.0                7
3        two        10.0               10
4      seven         9.0                6

In [ ]:
X.shape

(8, 3)

In [ ]:
X.experience

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [ ]:
# Converting text to nos

def conv(x):
    dict = { 'two':2, 'three':3, 'five':5, 'seven':7, 'ten':10, 0:0, 'eleven':11 }
    return dict[x]

In [ ]:
X['experience'] = X['experience'].apply(lambda x: conv(x))

In [ ]:
X.head()

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       8 non-null      int64  
 1   test_score       8 non-null      float64
 2   interview_score  8 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 320.0 bytes


__X is ready now.__

In [ ]:
y = df.iloc[:,-1]

In [ ]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [ ]:
y.shape

(8,)

We are not doing traintestsplit here as the dataset is very small. However, in real life modeling, you are encouraged to do it as you do for every other problem.

Our main agenda for today is just to focus on Deployment part.

__Q. You can select any of the projects covered till now by any of the trainers and deploy the same.__

In [ ]:
# Modeling

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
# Fit
lr.fit(X, y)

LinearRegression()

In [ ]:
# Prediction Phase

y_pred = lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [ ]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_pred, y)

0.9626511210293307

In [ ]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [ ]:
lr.predict([[3,9,7]]) # Test data

array([58315.5019167])

In [ ]:
lr.predict([[10,10,10]]) # Test data

array([86612.80419155])

In [ ]:
lr.predict([[10,2,3]]) # Test data

array([55930.47274854])

# Model Deployment

In [ ]:
import pickle

pickle.dump(lr, open('model.pkl','wb'))
# Dump this model called 'lr' by the name'model.pkl' in our systems HDD and while doing this
# write this file using "write bytes" mode.

In [ ]:
# Load the model --> Client Side

client_model = pickle.load(open('model.pkl','rb'))

In [ ]:
client_model.predict([[3,9,7]]) # Test data

array([58315.5019167])

In [ ]:
client_model.predict([[10,10,10]]) # Test data

array([86612.80419155])

In [ ]:
client_model.predict([[10,2,3]]) # Test data

array([55930.47274854])

# Happy Learning